package com.guppy.gallery.domain;

import com.guppy.gallery.repository.EpisodeRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ExtendWith(SpringExtension.class)
public class MongoDbAutoGeneratedFieldIntegrationTest {

    @Autowired
    private EpisodeRepository episodeRepository;

    @Test
    void givenEpisodeObject_whenSave_thenCreateNewEpisode(){
        // Given
        Episode episode = Episode.builder()
                .episodeName("첫번째 에피소드")
                .episodeDescription("구피 첫번째 에피소드")
                .build();

        // When
        episodeRepository.save(episode);

        // Then
        assertThat(episodeRepository.findAll().size()).isGreaterThan(0);
    }

}
