version: '3'

services:
  db:
    image: mongo

  spring:
    build:
      context: .
      dockerfile: docker/spring/Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=gallery
      - WAIT_HOSTS=db:27017
    ports:
      - "8080:8080"

  nginx:
    image: nginx
    depends_on:
      - spring
    volumes:
      - ./docker/nginx/app.conf.template:/etc/nginx/conf.d/app.conf.template
    ports:
      - "80:80"
    environment:
      - APP_HOST=spring
      - APP_PORT=8080
    command: /bin/bash -c "envsubst '$$APP_HOST $$APP_PORT' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"