version: '3'

services:
  db:
    image: mongo
    restart: always
    container_name: gallery-mongodb
    volumes:
      - ./init-user.js:/docker-entrypoint-initdb.d/init-user.js:ro
      - '/home/ec2-user/data/db:/data/db'
    environment:
      - MONGO_INITDB_DATABASE=gallery
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017

  spring:
    build:
      context: .
      dockerfile: docker/spring/Dockerfile
    container_name: gallery-spring
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=gallery
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"

  nginx:
    image: nginx
    container_name: gallery-nginx
    depends_on:
      - spring
    volumes:
      - ./docker/nginx/app.conf.template:/etc/nginx/conf.d/app.conf.template
    ports:
      - "80:80"
    environment:
      - APP_HOST=spring
      - APP_PORT=8080
    command: /bin/bash -c "envsubst '$$APP_HOST $$APP_PORT' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"